In [133]:
import numpy as np

In [134]:
a = np.arange(0, 10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [135]:
b = np.diag(np.arange(5, 50, 15))
b

array([[ 5,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 35]])

In [136]:
sum_ = 0
i = 0
while i < len(b):
    sum_ += b[i][i]
    i += 1
sum_

60

🔮  4x + 2y + z = 4

🧠  x + 3y = 12

✨  5y + 4z = -3

In [137]:
c = np.array( [ [4, 2, 1], [1, 3, 0 ] , [0, 5, 4] ] )

In [138]:
z = np.array( [4, 12, -3] )

In [139]:
from numpy import linalg

In [140]:
linalg.solve(c, z)

array([ 0.46666667,  3.84444444, -5.55555556])

In [141]:
np.allclose( np.dot(c, linalg.solve(c, z)), z )

True

In [142]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [143]:
users_stats

array([[2, 1, 0, 0, 0, 0],
       [1, 1, 2, 1, 0, 0],
       [2, 0, 1, 0, 0, 0],
       [1, 1, 2, 1, 0, 1],
       [0, 0, 1, 2, 0, 0],
       [0, 0, 0, 0, 0, 5],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 3],
       [1, 0, 0, 2, 1, 4]])

In [145]:
def cosine (a,b):
    aLenght = np.linalg.norm(a)
    bLenght = np.linalg.norm(b)
    return np.dot(a,b) / (aLenght * bLenght)
for i in users_stats:
    print(cosine(i, next_user_stats))
    break

0.19999999999999996
